# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configdialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ConfigDialog.resize(1058, 1023)
        ConfigDialog.setMinimumSize(QtCore.QSize(1054, 992))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(ConfigDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(ConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1042, 928))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_basic = QtWidgets.QWidget()
        self.tab_basic.setObjectName("tab_basic")
        self.groupBox = QtWidgets.QGroupBox(self.tab_basic)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1020, 885))
        self.groupBox.setMinimumSize(QtCore.QSize(1020, 885))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.use_html_file_check = QtWidgets.QCheckBox(self.groupBox)
        self.use_html_file_check.setGeometry(QtCore.QRect(30, 300, 951, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_html_file_check.sizePolicy().hasHeightForWidth())
        self.use_html_file_check.setSizePolicy(sizePolicy)
        self.use_html_file_check.setMinimumSize(QtCore.QSize(951, 241))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.use_html_file_check.setFont(font)
        self.use_html_file_check.setObjectName("use_html_file_check")
        self.use_images_check = QtWidgets.QCheckBox(self.groupBox)
        self.use_images_check.setGeometry(QtCore.QRect(30, 40, 981, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_images_check.sizePolicy().hasHeightForWidth())
        self.use_images_check.setSizePolicy(sizePolicy)
        self.use_images_check.setMinimumSize(QtCore.QSize(981, 241))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.use_images_check.setFont(font)
        self.use_images_check.setObjectName("use_images_check")
        self.use_menu_data_check = QtWidgets.QCheckBox(self.groupBox)
        self.use_menu_data_check.setGeometry(QtCore.QRect(30, 560, 991, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_menu_data_check.sizePolicy().hasHeightForWidth())
        self.use_menu_data_check.setSizePolicy(sizePolicy)
        self.use_menu_data_check.setMinimumSize(QtCore.QSize(981, 0))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.use_menu_data_check.setFont(font)
        self.use_menu_data_check.setObjectName("use_menu_data_check")
        self.tabWidget.addTab(self.tab_basic, "")
        self.tab_images = QtWidgets.QWidget()
        self.tab_images.setObjectName("tab_images")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_images)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 10, 1021, 121))
        self.groupBox_2.setMinimumSize(QtCore.QSize(1021, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(490, 30, 511, 71))
        self.label.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rotateTimeBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotateTimeBox.setGeometry(QtCore.QRect(310, 50, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateTimeBox.sizePolicy().hasHeightForWidth())
        self.rotateTimeBox.setSizePolicy(sizePolicy)
        self.rotateTimeBox.setMinimumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rotateTimeBox.setFont(font)
        self.rotateTimeBox.setDecimals(1)
        self.rotateTimeBox.setMinimum(0.5)
        self.rotateTimeBox.setMaximum(30.0)
        self.rotateTimeBox.setObjectName("rotateTimeBox")
        self.rotate_images_check = QtWidgets.QCheckBox(self.groupBox_2)
        self.rotate_images_check.setGeometry(QtCore.QRect(30, 30, 271, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_images_check.sizePolicy().hasHeightForWidth())
        self.rotate_images_check.setSizePolicy(sizePolicy)
        self.rotate_images_check.setMinimumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rotate_images_check.setFont(font)
        self.rotate_images_check.setObjectName("rotate_images_check")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_images)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 140, 1021, 601))
        self.groupBox_3.setMinimumSize(QtCore.QSize(1021, 601))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 971, 61))
        self.label_2.setMinimumSize(QtCore.QSize(971, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loadedContentWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.loadedContentWidget.setGeometry(QtCore.QRect(20, 100, 991, 271))
        self.loadedContentWidget.setMinimumSize(QtCore.QSize(991, 271))
        self.loadedContentWidget.setObjectName("loadedContentWidget")
        self.deleteSelectionButton = QtWidgets.QPushButton(self.groupBox_3)
        self.deleteSelectionButton.setGeometry(QtCore.QRect(570, 400, 261, 61))
        self.deleteSelectionButton.setMinimumSize(QtCore.QSize(261, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.deleteSelectionButton.setFont(font)
        self.deleteSelectionButton.setObjectName("deleteSelectionButton")
        self.addImageButton = QtWidgets.QPushButton(self.groupBox_3)
        self.addImageButton.setGeometry(QtCore.QRect(190, 400, 271, 61))
        self.addImageButton.setMinimumSize(QtCore.QSize(271, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addImageButton.setFont(font)
        self.addImageButton.setObjectName("addImageButton")
        self.tabWidget.addTab(self.tab_images, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.groupBox_4 = QtWidgets.QGroupBox(ConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(1040, 90))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.okCancelButtonBox = QtWidgets.QDialogButtonBox(self.groupBox_4)
        self.okCancelButtonBox.setGeometry(QtCore.QRect(-10, 20, 1040, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okCancelButtonBox.sizePolicy().hasHeightForWidth())
        self.okCancelButtonBox.setSizePolicy(sizePolicy)
        self.okCancelButtonBox.setMinimumSize(QtCore.QSize(1040, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.okCancelButtonBox.setFont(font)
        self.okCancelButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.okCancelButtonBox.setCenterButtons(False)
        self.okCancelButtonBox.setObjectName("okCancelButtonBox")
        self.verticalLayout_6.addWidget(self.groupBox_4)

        self.retranslateUi(ConfigDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Settings"))
        self.groupBox.setTitle(_translate("ConfigDialog", "Content"))
        self.use_html_file_check.setText(_translate("ConfigDialog", "Use HTML file"))
        self.use_images_check.setText(_translate("ConfigDialog", "Use images"))
        self.use_menu_data_check.setText(_translate("ConfigDialog", "Use menu data import"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_basic), _translate("ConfigDialog", "Basic"))
        self.groupBox_2.setTitle(_translate("ConfigDialog", "Rotation settings"))
        self.label.setText(_translate("ConfigDialog", "minutes"))
        self.rotate_images_check.setText(_translate("ConfigDialog", " Rotate Images every"))
        self.groupBox_3.setTitle(_translate("ConfigDialog", "Add/Remove"))
        self.label_2.setText(_translate("ConfigDialog", "Loaded Images:"))
        self.deleteSelectionButton.setText(_translate("ConfigDialog", "Delete Selection"))
        self.addImageButton.setText(_translate("ConfigDialog", "Add Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_images), _translate("ConfigDialog", "Images"))

