# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secdialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SecDialog(object):
    def setupUi(self, SecDialog):
        SecDialog.setObjectName("SecDialog")
        SecDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SecDialog.resize(568, 318)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(SecDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(SecDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(SecDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(0.5)
        self.doubleSpinBox.setMaximum(30.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox)
        self.label = QtWidgets.QLabel(SecDialog)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(SecDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.listView = QtWidgets.QListView(SecDialog)
        self.listView.setObjectName("listView")
        self.verticalLayout_6.addWidget(self.listView)
        self.pushButton_2 = QtWidgets.QPushButton(SecDialog)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(SecDialog)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.okCancelButtonBox = QtWidgets.QDialogButtonBox(SecDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.okCancelButtonBox.setFont(font)
        self.okCancelButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okCancelButtonBox.setObjectName("okCancelButtonBox")
        self.verticalLayout_6.addWidget(self.okCancelButtonBox)

        self.retranslateUi(SecDialog)
        QtCore.QMetaObject.connectSlotsByName(SecDialog)

    def retranslateUi(self, SecDialog):
        _translate = QtCore.QCoreApplication.translate
        SecDialog.setWindowTitle(_translate("SecDialog", "Dialog"))
        self.checkBox.setText(_translate("SecDialog", "Rotate Images every"))
        self.label.setText(_translate("SecDialog", "minutes"))
        self.label_2.setText(_translate("SecDialog", "Images:"))
        self.pushButton_2.setText(_translate("SecDialog", "Delete Selection"))
        self.pushButton.setText(_translate("SecDialog", "Add Image"))

