#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
BUILD_SCRIPT="$SCRIPT_DIR/build-dpkg.sh"
OVERLAY_DIR="$SCRIPT_DIR/overlay/opt/ezdmb"

if [[ ! -f "$BUILD_SCRIPT" ]]; then
    echo "Missing Debian build script: $BUILD_SCRIPT" >&2
    exit 1
fi

if ! command -v dpkg >/dev/null 2>&1; then
    echo "Error: dpkg is required for the verification flow. This script must run on a Debian/Ubuntu-based Linux system." >&2
    exit 1
fi

echo "==> Building Debian package with $BUILD_SCRIPT"
if ! bash "$BUILD_SCRIPT"; then
    echo "build-dpkg.sh failed." >&2
    exit 1
fi

deb_file="$(find "$SCRIPT_DIR" -maxdepth 1 -type f -name '*.deb' -print 2>/dev/null | sort | tail -n 1)"
if [[ -z "$deb_file" ]]; then
    echo "No .deb package was generated by build-dpkg.sh" >&2
    exit 1
fi

echo "==> Installing package with dpkg: $deb_file"
if [[ "$(id -u)" -eq 0 ]]; then
    dpkg -i --force-confnew "$deb_file"
else
    sudo dpkg -i --force-confnew "$deb_file"
fi

if [[ ! -d /opt/ezdmb ]]; then
    echo "/opt/ezdmb was not created during installation" >&2
    exit 1
fi

if [[ ! -d "$OVERLAY_DIR" ]]; then
    echo "Expected overlay directory not found: $OVERLAY_DIR" >&2
    exit 1
fi

# overlay_manifest="$(cd "$OVERLAY_DIR" && find . -mindepth 1 -print | LC_ALL=C sort)"
# installed_manifest="$(cd /opt/ezdmb && find . -mindepth 1 -print | LC_ALL=C sort)"

# if [[ "$overlay_manifest" != "$installed_manifest" ]]; then
#     echo "Installed files do not match the overlay contents." >&2
#     echo "--- overlay ---" >&2
#     printf '%s\n' "$overlay_manifest" >&2
#     echo "--- /opt/ezdmb ---" >&2
#     printf '%s\n' "$installed_manifest" >&2
#     exit 1
# fi

# for expected in ezdmb Resources; do
#     if [[ ! -e "/opt/ezdmb/$expected" ]]; then
#         echo "Missing expected installed path: /opt/ezdmb/$expected" >&2
#         exit 1
#     fi
# done

echo "Verification passed: build-dpkg.sh succeeded and /opt/ezdmb matches the overlay content."
