#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BUILD_SCRIPT="$SCRIPT_DIR/build-dpkg.sh"

if [[ ! -f "$BUILD_SCRIPT" ]]; then
    echo "Missing Debian build script: $BUILD_SCRIPT" >&2
    exit 1
fi

if ! command -v dpkg >/dev/null 2>&1; then
    echo "Error: dpkg is required for the verification flow. This script must run on a Debian/Ubuntu-based Linux system." >&2
    exit 1
fi

echo "==> Building Debian package with $BUILD_SCRIPT"
if ! bash "$BUILD_SCRIPT"; then
    echo "build-dpkg.sh failed." >&2
    exit 1
fi

deb_file="$(find "$SCRIPT_DIR/../python_package/ezdmb/resources/" -maxdepth 1 -type f -name '*.deb' -print 2>/dev/null | sort | tail -n 1)"
if [[ -z "$deb_file" ]]; then
    echo "No .deb package was generated by build-dpkg.sh" >&2
    exit 1
fi

echo "==> Installing package with dpkg: $deb_file"
if [[ "$(id -u)" -eq 0 ]]; then
    dpkg -i --force-confnew "$deb_file"
else
    sudo dpkg -i --force-confnew "$deb_file"
fi

echo "Verification passed: build-dpkg.sh succeeded, and the package was installed successfully."
