from pprint import pformat

from PyQt5.QtCore import QSize, Qt
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import (
    QCheckBox,
    QDialog,
    QDialogButtonBox,
    QDoubleSpinBox,
    QFileDialog,
    QFrame,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QListWidget,
    QListWidgetItem,
    QMessageBox,
    QPushButton,
    QSizePolicy,
    QTabWidget,
    QVBoxLayout,
    QWidget
)

from ezdmb.Controller import SqliteImporter


class ConfigDialog(QDialog):
    def __init__(self, config):
        super(self.__class__, self).__init__()
        self.setupUi(self)

        # Display list of loaded content files for the DMB in the loadedContentWidget
        for i in config.ContentArray:
            item = QListWidgetItem("%s" % str(i))
            self.loadedContentWidget.addItem(item)

        self._config = config
        self.okCancelButtonBox.rejected.connect(self.closeDialog)
        self.okCancelButtonBox.accepted.connect(self.saveAndClose)
        self.addImageButton.clicked.connect(self.addContent)
        self.deleteSelectionButton.clicked.connect(self.deleteSelectedContent)
        self.importButton.clicked.connect(self.importMenuToSqliteFromFile)

    def closeDialog(self):
        self.close()

    def saveAndClose(self):
        tmpContentList = [
            str(self.loadedContentWidget.item(i).text())
            for i in range(self.loadedContentWidget.count())
        ]
        self._config.SaveConfig(
            self.useImagesCheck.isChecked(),
            self.useHtmlFileCheck.isChecked(),
            self.useMenuDataCheck.isChecked(),
            self.rotateImagesCheck.isChecked(),
            float(self.rotateTimeBox.value()),
            tmpContentList,
        )

        self._config.UseImages = self.useImagesCheck.isChecked()
        self._config.UseHTML = self.useHtmlFileCheck.isChecked()
        self._config.UseImported = self.useMenuDataCheck.isChecked()
        self._config.RotateContent = self.rotateImagesCheck.isChecked()
        self._config.RotateContentTime = self.rotateTimeBox.value()
        self._config.ContentArray = tmpContentList
        self.close()

    def addContent(self):
        contentFile = QFileDialog.getOpenFileName(self)[0]
        self.loadedContentWidget.addItem(contentFile)

    def deleteSelectedContent(self):
        for SelectedItem in self.loadedContentWidget.selectedItems():
            self.loadedContentWidget.takeItem(
                self.loadedContentWidget.row(SelectedItem)
            )

    def setUiFromConfig(self):
        self.useImagesCheck.setChecked(bool(self._config.UseImages))
        self.useHtmlFileCheck.setChecked(bool(self._config.UseHTML))
        self.useMenuDataCheck.setChecked(bool(self._config.UseImported))
        self.rotateImagesCheck.setChecked(bool(self._config.RotateContent))
        self.rotateTimeBox.setValue(float(self._config.RotateContentTime))

    def importMenuToSqliteFromFile(self):
        importer = SqliteImporter.SqliteImporter()
        menuFile = QFileDialog.getOpenFileName(self)[0]
        try:
            menuData = importer.ImportMenuToSqliteFromFile(menuFile)
        except AttributeError:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Could not load menu file.")
            msg.setInformativeText('The menu file could not be loaded; Please make sure the menu file is in the proper format.')
            msg.setWindowTitle("Could not load menu file.")
            msg.exec_()

        self.menuLbl.text = pformat(menuData)

    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.setWindowModality(Qt.ApplicationModal)
        ConfigDialog.resize(401, 331)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConfigDialog.sizePolicy().hasHeightForWidth())
        ConfigDialog.setSizePolicy(sizePolicy)
        ConfigDialog.setMinimumSize(QSize(400, 300))
        self.verticalLayout_6 = QVBoxLayout(ConfigDialog)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.settingsTabs = QTabWidget(ConfigDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsTabs.sizePolicy().hasHeightForWidth())
        self.settingsTabs.setSizePolicy(sizePolicy)
        self.settingsTabs.setMinimumSize(QSize(200, 180))
        font = QFont()
        font.setPointSize(20)
        self.settingsTabs.setFont(font)
        self.settingsTabs.setTabPosition(QTabWidget.North)
        self.settingsTabs.setTabShape(QTabWidget.Rounded)
        self.settingsTabs.setObjectName("settingsTabs")
        self.typesTab = QWidget()
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typesTab.sizePolicy().hasHeightForWidth())
        self.typesTab.setSizePolicy(sizePolicy)
        self.typesTab.setMinimumSize(QSize(500, 300))
        self.typesTab.setObjectName("typesTab")
        self.verticalLayout_4 = QVBoxLayout(self.typesTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QGroupBox(self.typesTab)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QSize(100, 100))
        font = QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.useImagesCheck = QCheckBox(self.groupBox)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useImagesCheck.sizePolicy().hasHeightForWidth())
        self.useImagesCheck.setSizePolicy(sizePolicy)
        self.useImagesCheck.setMinimumSize(QSize(100, 40))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.useImagesCheck.setFont(font)
        self.useImagesCheck.setObjectName("useImagesCheck")
        self.verticalLayout.addWidget(self.useImagesCheck)
        self.useHtmlFileCheck = QCheckBox(self.groupBox)
        self.useHtmlFileCheck.setMinimumSize(QSize(100, 40))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.useHtmlFileCheck.setFont(font)
        self.useHtmlFileCheck.setObjectName("useHtmlFileCheck")
        self.verticalLayout.addWidget(self.useHtmlFileCheck)
        self.useMenuDataCheck = QCheckBox(self.groupBox)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useMenuDataCheck.sizePolicy().hasHeightForWidth())
        self.useMenuDataCheck.setSizePolicy(sizePolicy)
        self.useMenuDataCheck.setMinimumSize(QSize(100, 40))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.useMenuDataCheck.setFont(font)
        self.useMenuDataCheck.setObjectName("useMenuDataCheck")
        self.verticalLayout.addWidget(self.useMenuDataCheck)
        self.okCancelButtonBox = QDialogButtonBox(self.groupBox)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okCancelButtonBox.sizePolicy().hasHeightForWidth())
        self.okCancelButtonBox.setSizePolicy(sizePolicy)
        self.okCancelButtonBox.setMinimumSize(QSize(140, 30))
        font = QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.okCancelButtonBox.setFont(font)
        self.okCancelButtonBox.setLayoutDirection(Qt.LeftToRight)
        self.okCancelButtonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Save)
        self.okCancelButtonBox.setCenterButtons(True)
        self.okCancelButtonBox.setObjectName("okCancelButtonBox")
        self.verticalLayout.addWidget(self.okCancelButtonBox)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.settingsTabs.addTab(self.typesTab, "")
        self.contentTab = QWidget()
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentTab.sizePolicy().hasHeightForWidth())
        self.contentTab.setSizePolicy(sizePolicy)
        self.contentTab.setMinimumSize(QSize(300, 100))
        self.contentTab.setObjectName("contentTab")
        self.verticalLayout_5 = QVBoxLayout(self.contentTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QGroupBox(self.contentTab)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QSize(180, 80))
        font = QFont()
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rotateImagesCheck = QCheckBox(self.groupBox_2)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateImagesCheck.sizePolicy().hasHeightForWidth())
        self.rotateImagesCheck.setSizePolicy(sizePolicy)
        self.rotateImagesCheck.setMinimumSize(QSize(180, 24))
        font = QFont()
        font.setPointSize(11)
        self.rotateImagesCheck.setFont(font)
        self.rotateImagesCheck.setObjectName("rotateImagesCheck")
        self.horizontalLayout_2.addWidget(self.rotateImagesCheck)
        self.rotateTimeBox = QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateTimeBox.sizePolicy().hasHeightForWidth())
        self.rotateTimeBox.setSizePolicy(sizePolicy)
        self.rotateTimeBox.setMinimumSize(QSize(70, 24))
        font = QFont()
        font.setPointSize(11)
        self.rotateTimeBox.setFont(font)
        self.rotateTimeBox.setDecimals(1)
        self.rotateTimeBox.setMinimum(0.5)
        self.rotateTimeBox.setMaximum(30.0)
        self.rotateTimeBox.setObjectName("rotateTimeBox")
        self.horizontalLayout_2.addWidget(self.rotateTimeBox)
        self.label = QLabel(self.groupBox_2)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(50, 31))
        font = QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QGroupBox(self.contentTab)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QSize(180, 140))
        font = QFont()
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QLabel(self.groupBox_3)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(200, 32))
        font = QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.loadedContentWidget = QListWidget(self.groupBox_3)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadedContentWidget.sizePolicy().hasHeightForWidth())
        self.loadedContentWidget.setSizePolicy(sizePolicy)
        self.loadedContentWidget.setMinimumSize(QSize(200, 20))
        self.loadedContentWidget.setObjectName("loadedContentWidget")
        self.verticalLayout_2.addWidget(self.loadedContentWidget)
        self.frame = QFrame(self.groupBox_3)
        self.frame.setMinimumSize(QSize(180, 40))
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(6, 3, 6, 8)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addImageButton = QPushButton(self.frame)
        self.addImageButton.setMinimumSize(QSize(120, 36))
        font = QFont()
        font.setPointSize(12)
        self.addImageButton.setFont(font)
        self.addImageButton.setObjectName("addImageButton")
        self.horizontalLayout.addWidget(self.addImageButton)
        self.deleteSelectionButton = QPushButton(self.frame)
        self.deleteSelectionButton.setMinimumSize(QSize(120, 36))
        font = QFont()
        font.setPointSize(12)
        self.deleteSelectionButton.setFont(font)
        self.deleteSelectionButton.setObjectName("deleteSelectionButton")
        self.horizontalLayout.addWidget(self.deleteSelectionButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.settingsTabs.addTab(self.contentTab, "")
        self.importTab = QWidget()
        self.importTab.setObjectName("importTab")
        self.verticalLayout_7 = QVBoxLayout(self.importTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.currentImportedMenuDataBox = QGroupBox(self.importTab)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentImportedMenuDataBox.sizePolicy().hasHeightForWidth())
        self.currentImportedMenuDataBox.setSizePolicy(sizePolicy)
        self.currentImportedMenuDataBox.setMinimumSize(QSize(100, 100))
        font = QFont()
        font.setPointSize(16)
        self.currentImportedMenuDataBox.setFont(font)
        self.currentImportedMenuDataBox.setObjectName("currentImportedMenuDataBox")
        self.verticalLayout_3 = QVBoxLayout(self.currentImportedMenuDataBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menuLbl = QLabel(self.currentImportedMenuDataBox)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuLbl.sizePolicy().hasHeightForWidth())
        self.menuLbl.setSizePolicy(sizePolicy)
        self.menuLbl.setMinimumSize(QSize(0, 0))
        self.menuLbl.setText("")
        self.menuLbl.setObjectName("menuLbl")
        self.verticalLayout_3.addWidget(self.menuLbl)
        self.verticalLayout_7.addWidget(self.currentImportedMenuDataBox)
        self.importMenuDataBox = QGroupBox(self.importTab)
        font = QFont()
        font.setPointSize(16)
        self.importMenuDataBox.setFont(font)
        self.importMenuDataBox.setTitle("")
        self.importMenuDataBox.setAlignment(Qt.AlignCenter)
        self.importMenuDataBox.setFlat(True)
        self.importMenuDataBox.setObjectName("importMenuDataBox")
        self.verticalLayout_8 = QVBoxLayout(self.importMenuDataBox)
        self.verticalLayout_8.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.importButton = QPushButton(self.importMenuDataBox)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setMinimumSize(QSize(200, 60))
        self.importButton.setObjectName("importButton")
        self.verticalLayout_8.addWidget(self.importButton)
        self.verticalLayout_7.addWidget(self.importMenuDataBox)
        self.settingsTabs.addTab(self.importTab, "")
        self.verticalLayout_6.addWidget(self.settingsTabs)

        self.retranslateUi(ConfigDialog)
        self.settingsTabs.setCurrentIndex(0)

    def retranslateUi(self, ConfigDialog):
        ConfigDialog.setWindowTitle("Settings")
        self.useImagesCheck.setText("Use images")
        self.useHtmlFileCheck.setText("Use HTML files")
        self.useMenuDataCheck.setText("Use menu data import")
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.typesTab), "Types")
        self.groupBox_2.setTitle("Rotation settings")
        self.rotateImagesCheck.setText(" Rotate content every")
        self.label.setText("minutes")
        self.groupBox_3.setTitle("Add/Remove")
        self.label_2.setText("Loaded content:")
        self.addImageButton.setText("Add Content")
        self.deleteSelectionButton.setText("Delete Selection")
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.contentTab), "Content")
        self.currentImportedMenuDataBox.setTitle("Current Imported Menu Data")
        self.importButton.setText("Import from file")
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.importTab), "Import")
