from PyQt5.QtCore import QSize, Qt
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QFrame, QGridLayout, QHBoxLayout, QSizePolicy, QToolButton, QWidget


class NavHeader(QWidget):
    def __init__(self, parent):
        super(self.__class__, self).__init__(parent)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(256, 34)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(150, 32))
        self.gridLayout = QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QFrame(Form)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(160, 32))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsButton = QToolButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setMinimumSize(QSize(50, 32))
        font = QFont()
        font.setPointSize(14)
        self.settingsButton.setFont(font)
        self.settingsButton.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout.addWidget(self.settingsButton, 0, Qt.AlignLeft)
        self.checkButton = QToolButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkButton.sizePolicy().hasHeightForWidth())
        self.checkButton.setSizePolicy(sizePolicy)
        self.checkButton.setMinimumSize(QSize(50, 32))
        font = QFont()
        font.setPointSize(14)
        self.checkButton.setFont(font)
        self.checkButton.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout.addWidget(self.checkButton)
        self.resultsButton = QToolButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsButton.sizePolicy().hasHeightForWidth())
        self.resultsButton.setSizePolicy(sizePolicy)
        self.resultsButton.setMinimumSize(QSize(50, 32))
        font = QFont()
        font.setPointSize(14)
        self.resultsButton.setFont(font)
        self.resultsButton.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.resultsButton.setObjectName("resultsButton")
        self.horizontalLayout.addWidget(self.resultsButton)
        self.aboutButton = QToolButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutButton.sizePolicy().hasHeightForWidth())
        self.aboutButton.setSizePolicy(sizePolicy)
        self.aboutButton.setMinimumSize(QSize(50, 32))
        font = QFont()
        font.setPointSize(14)
        self.aboutButton.setFont(font)
        self.aboutButton.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout.addWidget(self.aboutButton, 0, Qt.AlignRight)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle("Form", "Form")
        Form.setAccessibleName("Form", "navHeaderForm")
        self.frame.setAccessibleName("Form", "navHeaderFrame")
        self.settingsButton.setAccessibleName("Form", "settingsBtn")
        self.settingsButton.setText("Form", "Settings")
        self.checkButton.setText("Form", "Check")
        self.resultsButton.setAccessibleName("Form", "resultsBtn")
        self.resultsButton.setText("Form", "Results")
        self.aboutButton.setAccessibleName("Form", "aboutBtn")
        self.aboutButton.setText("Form", "About")