name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    compile-windows-exe:
        name: Compile Windows Executable
        runs-on: windows-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Build the project
            run: |
              pip install -r requirements.txt
              cd src/ezdmb
              pyinstaller --onefile __main__.py
              cd dist
              ren "__main__.exe" "ezdmb.exe" 
          - name: Upload the executable
            uses: actions/upload-artifact@v4
            with:
              name: ezdmb.exe
    compile-installer:
        name: Build and run the container
        runs-on: ubuntu-latest
        steps:
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: rancorsoft1/ezdmb:latest
          - name: Check out the repo
            uses: actions/checkout@v2
          - uses: actions/download-artifact@v4
            with:
              name: ezdmb.exe
          - name: Move the executable to artifact directory
            run: mv ezdmb.exe ${{ github.workspace }}/artifacts/ezdmb.exe
          - name: Run the installer build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: rancorsoft1/ezdmb:latest
                options: -v ${{ github.workspace }}:/work --user root
                run: |
                    iscc ezdmb-installer.iss
          - uses: actions/upload-artifact@v4
            with:
              name: ezdmb_installer.exe
              path: ezdmb_installer.exe
