name: Build windows installer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run bash script
        run: bash cd windows && ./build-install.sh
