name: Windows installer build bundle

on:
  push:
    tags:
    - 'v*'

jobs:
    compile-windows-exe:
        name: Build Windows Executable
        runs-on: windows-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Build the project
            run: |
              pip install -r requirements.txt
              cd src/ezdmb
              pyinstaller --onefile __main__.py
              cd dist
              ren "__main__.exe" "ezdmb.exe" 
          - name: Upload the executable
            uses: actions/upload-artifact@v4
            with:
              name: ezdmb.exe
              path: src/ezdmb/dist/ezdmb.exe
              retention-days: 1

    compile-installer:
        needs: compile-windows-exe
        name: Build windows installer exe
        runs-on: ubuntu-latest

        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - uses: actions/download-artifact@v4
            with:
              name: ezdmb.exe
          - name: Move exe to build artifacts directory
            run:  mv ezdmb.exe artifacts/
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: rancorsoft1/ezdmb:latest
          - name: Run the installer build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: rancorsoft1/ezdmb:latest
                options: -v ${{ github.workspace }}:/work --user root
                run: |
                    iscc ezdmb-installer.iss
          - uses: actions/upload-artifact@v4
            with:
              name: ezdmb_setup.exe
              path: ezdmb_setup.exe
              retention-days: 1

    bundle-install-scripts:
        # This job bundles the installer exe with install.bat and child.ps1
        needs: compile-installer
        name: Bundle installer with necessary platform scripts
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - uses: actions/download-artifact@v4
            with:
              name: ezdmb_setup.exe
          - name: Move installer exe to build artifacts directory
            run:  mv ezdmb_setup.exe artifacts/
          - name: Bundle installer with scripts
            run: |
              mkdir -p installbundle
              ls -la
              cp artifacts/ezdmb_setup.exe installbundle/
              cp windows/windows_install/install.bat installbundle/
              cp windows/windows_install/child.ps1 installbundle/
              zip -j -r ezdmb_install.zip installbundle
          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ github.ref }}
              release_name: Release ${{ github.ref }}
              draft: false
              prerelease: false
          - name: Upload Release Asset
            id: upload-release-asset 
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              # This pulls from the CREATE RELEASE step above, referencing it's ID to get its 
              # outputs object, which include a `upload_url`. See this blog post for more info:
              # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ezdmb_install.zip
              asset_name: ezdmb_install.zip
              asset_content_type: application/zip
